version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - revive
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
